        
# 일기예보 프로그램
print('날씨 정보를 입력하세요')
daylist = ['월', '화', '수', '목', '금', '토', '일']
day = input('요일을 입력하세요 \n')
date = input('오늘 날짜를 입력하세요 \n')
temp = input('기온을 입력하세요 \n')
maxtemp = input('낮 최고 기온을 입력하세요 \n')
rainposs = input('비 올 확률을 입력하세요 \n')
aircon = input('미세먼지 수치를 입력하세요 \n')
sunrise = input('일출 시간를 입력하세요 \n')
sunset = input('일몰 시간를 입력하세요 \n')
sthwave = input('남해 바다 높이를 입력하세요 \n')
estwave = input('동해 바다 높이를 입력하세요 \n')
wstwave = input('서해 바다 높이를 입력하세요 \n')
print('--------------------')
print('내일 날씨 예보입니다.')
print(daylist[0] + '요일인 ' + date + '의 아침 최저 기온은 ' + temp + '도, 낮 최고 기온은 ' + maxtemp + '도로 예보됐습니다.')
print('비 올 확률은 ' + rainposs + '%이고, 미세먼지는' + aircon + ' 수준일 것으로 예상됩니다.')
print('일출 시간은 ' + sunrise + '이고, 일몰 시간은 ' + sunset + '입니다.')
print('바다의 물결은 남해 앞바다 ' + sthwave + 'm, 동해 앞바다 ' + estwave + 'm, 서해 앞바다 ' + wstwave + ' 높이로 일겠습니다.')
print('지금까지 ' + date + ' ' + daylist[0] + '요일 날씨 예보였습니다.')
print('====================')
print('내일 날씨 예보입니다.')
print(daylist[0], '요일인', date, '의 아침 최저 기온은', temp, '도, 낮 최고 기온은', maxtemp, '도로 예보됐습니다.')
print('비 올 확률은', rainposs, '%이고, 미세먼지는', aircon, '수준일 것으로 예상됩니다.')
print('일출 시간은', sunrise, '이고, 일몰 시간은', sunset, '입니다.')
print('바다의 물결은 남해 앞바다', sthwave, 'm, 동해 앞바다', estwave, 'm, 서해 앞바다', wstwave, '높이로 일겠습니다.')
print('지금까지', date, daylist[0], '요일 날씨 예보였습니다.')
print('--------------------')
print('내일 날씨 예보입니다.')
print('{0}요일인 {1}의 아침 최저 기온은 {2}도, 낮 최고 기온은 {3}도로 예보됐습니다.'.format(day, date, temp, maxtemp))
print('비 올 확률은 {0}%이고, 미세먼지는 {1} 수준일 것으로 예상됩니다.'.format(rainposs, aircon))
print('일출 시간은 {0}이고, 일몰 시간은 {1}입니다.'.format(sunrise, sunset))
print('바다의 물결은 남해 앞바다 {0}m, 동해 앞바다 {1}m, 서해 앞바다 {2}높이로 일겠습니다.'.format(sthwave, estwave, wstwave))
print('지금까지 {0} {1}요일 날씨 예보였습니다.'.format(date, day))
print('====================')
# print('%s 요일인 %s의 아침 최저 기온은 %d도, 낮 최고 기온은 %d도로 예보됐습니다.'%(day, date, temp, maxtemp))
# print('비 올 확률은 %d이고, 미세먼지는 %s 수준일 것으로 예상됩니다.'%(rainposs, aircon))
# print('일출 시간은 %s이고, 일몰 시간은 %s입니다.'%(sunrise, sunset))
# print('바다의 물결은 남해 앞바다 %fm, 동해 앞바다 %fm, 서해 앞바다 %fm 높이로 일겠습니다.'%(sthwave. estwave, wstwave))
# print('지금까지 %s %s요일 날씨 예보였습니다.'%(date, day))